development:
  auth0_domain: dev-34uxk670t4va6l0u.us.auth0.com
  auth0_client_id: C5gXQ6Y4gS4bzWYc7y6N8f8fsLoWgwFO
  auth0_client_secret: p65xP18fOHwdOr8RH6vWXW4B1vWbpq_e2vJy50OgczaIyzwdvAploeOnZ8-R6M_B